const UserActionTypes = {
  CHECK_USER_SESSION_START: "CHECK_USER_SESSION_START",
  CHECK_USER_SESSION_SUCCESS: "CHECK_USER_SESSION_SUCCESS",

  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",

  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",


  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  ADD_ADDRESS_START: "ADD_ADDRESS_START",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",

  DELETE_ADDRESS_START: "DELETE_ADDRESS_START",
  DELETE_ADDRESS_SUCCESS: "DELETE_ADDRESS_SUCCESS",
  DELETE_ADDRESS_FAILURE: "DELETE_ADDRESS_FAILURE",

  EDIT_ADDRESS_START: "EDIT_ADDRESS_START",
  EDIT_ADDRESS_SUCCESS: "EDIT_ADDRESS_SUCCESS",
  EDIT_ADDRESS_FAILURE: "EDIT_ADDRESS_FAILURE",

  TOGGLE_DROPDOWN: "TOGGLE_DROPDOWN",
};

export default UserActionTypes;
